# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85a5ab9c62c86eb03c2819f64a29024d9b98d81d9264ba9da525ad9d670a90fb0d3a564dc72a329e585f8b2f20ca7e70d55108477ea0278ad75f31d1237dc9f5

test:
  secret_key_base: 82f343a76553e14f18ba265a819a0b5c7d69bf5fbee197a70ee7cb5e550b3f650c67c76e2f51508357dfef1453d205d58991bc188f828aa6df240a27a7603512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
